### ISSUE TITLE
treatment of missing data in ethnologue

### ISSUE THREAD

**Issue by HedvigS** [OlenaShcherbakova/Sociodemographic_factors_complexity#22]
@OlenaShcherbakova @SimonGreenhill I'm homesick, but I saw the emails today regarding Koplenig's letter.

I took a look at our code, and confirmed what I thought which is that there is a difference between <null> (_NA_) and 0, and we filter out all rows with missing values. However, to my annoyance, I discovered what may be a package-version issue. dplyr::filter used to take column names in double quote marks, but now apparently prefers ticks or no quote marks if the column name doesn't contain spaces etc. See [this commit](https://github.com/OlenaShcherbakova/Sociodemographic_factors_complexity/compare/main...ethnologye_pop_filter_change).

I would like to follow up by using groundhogr to test the behaviour of dplyr at an earlier time. I'm not working 100% right now, if you could help I'd appreciate that.

I've also looked up the documentation in the product we bought, and L2_users are not included. More on that in email chain.

**Comment by OlenaShcherbakova** [comment]
A brief update on this: I am currently on dplyr 1.1.2 (i.e. not the latest 1.1.3) and `filter`ing e.g. like this `filter(!is.na(All_Users))`  does the job for me (as does `filter(!is.na(`All_Users`))`).

**Comment by HedvigS** [comment]
> A brief update on this: I am currently on dplyr 1.1.2 (i.e. not the latest 1.1.3) and `filter`ing e.g. like this `filter(!is.na(All_Users))` does the job for me (as does `filter(!is.na(`All_Users`))`).

And what about with double quote marks instead of back-ticks?

**Comment by OlenaShcherbakova** [comment]
Sorry for the delay. I wanted to properly look into it. With double quotes it indeed does not work...
So this in combination with the below code messes with 23 languages which we now exclude from the final sample.
```
summarise(All_Users = sum(All_Users, na.rm = T),
            L1_Users = sum(L1_Users, na.rm = T), 
            ISO_639 = paste0(ISO_639, collapse = "; "))
```

**Comment by HedvigS** [comment]
I wonder when that different behaviour in dplyr crept in, because it did work as expected when we ran it last year.

**Comment by SamPassmore** [comment]
It might be worth writing dplyr::filter and dplyr::summarise just to be sure that you are calling the right / same function. 

I've run into problems in the past where filter is being called from base R, rather than dplyr. Both functions are common names, so its possible that other packages also use these function names.

**Comment by HedvigS** [comment]
That's a good point. i've started writing out package name for more and more functions. I've always written "dplyr::select" but now I'll start with filter too

**Comment by HedvigS** [comment]
It should be backticks or no markers, double quote marks is wrong. This is fixed in a new branch and will be the case in new analysis.
