### ISSUE TITLE
make_ethnologue_SM_for_morphological_complexity_reanalysis.R

### ISSUE THREAD

**Issue by HedvigS** [OlenaShcherbakova/Sociodemographic_factors_complexity#24]
We need to decide if we are modifying make_ethnologue_SM_for_morphological_complexity_reanalysis.R as well, or deleting it as the other script already makes the reduced publisbale tables.

**Comment by OlenaShcherbakova** [comment]
I have only managed to go over the core scripts so far.
This script creates the file for the extra WALS/complexity scores analysis.
I think we should incorporate it too and rerun it as well.

**Comment by OlenaShcherbakova** [comment]
Done.
